### ISSUE TITLE
User wants "hg19" as genome option

### ISSUE THREAD

**Issue by iskandr** [openvax/isovar#87]
Email from Wenhui Li:

> 
> 
> When I run isovar with parameter " --genome hg19", error occurs. The Error message is the following:
> 
> -----------------------------------
> 
> Traceback (most recent call last):
> 
>   File "/hwfssz1/ST_PRECISION/USER/liwenhui/01.Software/02.common/anaconda2/bin/isovar-protein-sequences.py", line 4, in <module>
> 
>     __import__('pkg_resources').run_script('isovar==0.7.0', 'isovar-protein-sequences.py')
> 
>   File "/hwfssz1/ST_PRECISION/USER/liwenhui/01.Software/02.common/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
> 
>   File "/hwfssz1/ST_PRECISION/USER/liwenhui/01.Software/02.common/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
> 
>   File "/hwfssz1/ST_PRECISION/USER/liwenhui/01.Software/02.common/anaconda2/lib/python2.7/site-packages/isovar-0.7.0-py2.7.egg/EGG-INFO/scripts/isovar-protein-sequences.py", line 46, in <module>
> 
> 
> 
>   File "build/bdist.linux-x86_64/egg/isovar/cli/protein_sequences.py", line 72, in protein_sequences_dataframe_from_args
> 
>   File "build/bdist.linux-x86_64/egg/isovar/cli/protein_sequences.py", line 60, in protein_sequences_generator_from_args
> 
>   File "build/bdist.linux-x86_64/egg/isovar/cli/rna_reads.py", line 79, in allele_reads_generator_from_args
> 
>   File "/hwfssz1/ST_PRECISION/USER/liwenhui/01.Software/02.common/anaconda2/lib/python2.7/site-packages/varcode-0.5.15-py2.7.egg/varcode/cli/variant_args.py", line 101, in variant_collection_from_args
> 
>     genome = genome_for_reference_name(args.genome)
> 
>   File "build/bdist.linux-x86_64/egg/pyensembl/__init__.py", line 51, in genome_for_reference_name
> 
>   File "build/bdist.linux-x86_64/egg/pyensembl/species.py", line 138, in normalize_reference_name
> 
> ValueError: Reference genome 'hg19' not found
> 
> ----------------------------------------------------------------------------------------------
> 
> 
> 
> I want to know how to use the parameter " --genome" to set genome reference (such as Ensembl, or refseq). Would you please to give me some guide? Thank you!
> 
> 
> 
> Looking forward to your reply.
> 
> 
> 
> Ms. Wenhui Li
> 
> Bioinformatics Analyst in BGI, Shenzhen, China
> 
> 
>

**Comment by iskandr** [comment]
`--genome hg19` works in current releases: Varcode maps UCSC names to the matching Ensembl assembly (hg19 → GRCh37, release 75), and `isovar run --help` lists it as an example. Closing.
